### PR TITLE
Schematics

### PR DESCRIPTION
**Pull request by scano16434**
Schematics for use with bq24560 or lt3652 solar charger controllers. Theyre SMD so currently looking for other options

### CODE REVIEW

**Comment by SillyInventor** [comment]
Please change the folder name. Labeling it new project may conflict with other projects and isn't descriptive.

**Comment by scano16434** [comment]
Wasn't sure how to directly change the name of the directory so i tried removing the new_project directory and adding one with a new name

**Comment by SillyInventor** [comment]
Hehe, that just created a new folder. You didn't delete the old one.

**Review by SillyInventor — APPROVED** [review]
LGTM

**Pull request merged**
