### PR TITLE
Initconductivity tester

### PR DESCRIPTION
**Pull request by FlyingcatX96**

### CODE REVIEW

**Comment by SillyInventor** [comment]
I am not familiar with the configuration of the opamps in concepts 1 & 2. Why is the output tied to +?

Surrounding the hair with a liquid metal is a good thought, but I think it might be overkill for a starter design. I think that mostly becauge 1gohm is a lot compared to most contact problems. I would suggest just clamping with copper to start with, and if the contact is really that hard to make, we'll switch over.

**Comment by FlyingcatX96** [comment]
Hi, 
From left to right the first set of two op-amps (same configuration) are voltage followers. I decided to use this to take advantage of the high input impedance of the op-amp and prevent changing voltage across the test resistor (hair). The second op-amp is a subtractor circuit. Since we're taking differential voltage measurements across two nodes of the bridge, the voltage across two points should be subtracted. The last op-amp in concept two is simply shifting the voltage range from +- 2.5V to a range of 0V to 5V, which is then useable by Arduino ADC

**Comment by SillyInventor** [comment]
Yeah... that's what I thought they were for... you've hooked up the opamps incorrectly then. The output should connect to the negative input of the opamp, not the positive.

**Comment by FlyingcatX96** [comment]
oops. I'll fix it once I get home. Is there anything else I should do or is this what is expected for week one?

**Comment by SillyInventor** [comment]
Week 1 is meant to be an easy step getting in. Now that you've outlined your work, you should be able to start putting that together and trying things out. Normally that would be a smoother transition... but the meeting was canceled.

**Comment by FlyingcatX96** [comment]
So if my understanding is correct I should start building circuits and test around with a resistor simulating hair since we do not have a hair sample. Is there any place I can get supplies like op-amps and the high resistance resistors (mainly 1 giga-ohms ones, but it would be nice to have some 1% resistors for the rest of the circuit as well, most of the labs have 5% resistors). I also have some Arduino Nanos laying around so I can try reading the output with its ADC

**Comment by FlyingcatX96** [comment]
Should be fixed now

**Comment by SillyInventor** [comment]
You can come to my office, I can give you resistors and opamps.
I don't have any 1 gohm resistors atm though. You will need to use a second strand of hair to balance it, while I put in an order.

**Review by SillyInventor — APPROVED** [review]
LGTM

**Pull request merged**
