### PR TITLE
<This folder contains schematics and circuit designs for the hair str…

### PR DESCRIPTION
**Pull request by SillyInventor**
…ength testing system, and the filr readme will have a more elaborated instructions and introductions.>

### CODE REVIEW

**Comment by SillyInventor** [comment]
@nickycheng4 when you want me to review your work, you should create a pull request like this one.

Some notes:

- When I said drawings, I was thinking more about the physical layout... how which parts connect and where
- +1 for having a readme. However, it shoudn't be a .docx, which is both an aweful format and propietary. Please use markdown / plain text like the readme in the base directory of this repo.
- Are you going to put your wheatstone into a opamp?

Fix the above tonight and come get your stuff when you have time... I think I may be running low on stepper motors, but if I don't have any when you come, you may simply pull on the hair with your fingers for a test.

**Comment by SillyInventor** [comment]
Also, @nickycheng4, the first line of the commit message is the title, the rest is the description. And you don't need '<' or '>' characters.

**Comment by nickycheng4** [comment]
Hello Professor,

I will fix these tonight, and when are you in the office tomorrow? I can come and pick the stuffs up.

Thanks.

Best,
Nicolas

**Comment by SillyInventor** [comment]
I will be in 10-12, 12:30-5.

**Comment by SillyInventor** [comment]
For future reference, markdown (the instruction file) has mathimatical notation:
http://csrgxtu.github.io/2015/03/20/Writing-Mathematic-Fomulars-in-Markdown/

**Pull request merged**
